### ISSUE TITLE
🚀 Feature: Fail Workflow on CI Conditions

### ISSUE THREAD

**Issue by DevGlitch** [DevGlitch/flutter-ci-checks#2]
## **Summary**
Add a feature to the Flutter CI GitHub Action that allows users to **fail the workflow** based on specific conditions like:

* 📦 Presence of upgradable or resolvable dependencies
* 🧹 Lint issues found during `flutter analyze`
* 📉 Test coverage falling below a user-defined threshold

## **Why?**
CI is only as useful as the standards it enforces. Sometimes just reporting issues isn't enough — teams want to enforce quality gates and stop bad builds from merging.

**Proposed Config Options (via `with:` or env vars)**

```yaml
with:
  fail_on_outdated: true         # fail if any outdated deps (upgradable or resolvable)
  fail_on_lint_issues: true      # fail if any analysis issues
  coverage_threshold: 80         # fail if coverage < 80%
```

## **Example Use Case**

```yaml
- name: Flutter CI
  uses: your-org/flutter-ci-action@v1
  with:
    fail_on_outdated: true
    fail_on_lint_issues: true
    coverage_threshold: 85
```

If any of those conditions are met, the action should exit non-zero and fail the job. Ideal for enforcing standards on PRs.
